objective: null
education:
- *uiuc_ms
- << : *uiuc_bs
  highlights: []
work:
- *ra
- <<: *del
  highlights:
  - *autofeed
  - *mptcp
  - *cowtv
- *nyx
- <<: *rvbd
  highlights:
  - *azure
  - *exchange
  - *intern
- <<: *locus
  highlights:
  - *locus-exp
  - *locus-software
  - *locus-webapp
- *nettech
skills:
- keywords:
  - *prog-skills
other: null
publications: null
